#define DISPLAY_OFF		0xAE
#define DISPLAY_ON		0xAF
#define DISPLAY_START_LINE_SET
#define PAGE_ADDRESS_SET
#define COLUMN_ADDRESS_SET_UPPER_BIT
#define COLUMN_ADDRESS_SET_LOWER_BIT
#define DISPLAY_DATA_WRITE
#define ADC_SELECT_NORMAL
#define ADC_SELECT_REVERSE
#define DISPLAY_NORMAL
#define DISPLAY_REVERSE
#define DISPLAY_ALL_POINTS_OFF
#define DISPLAY_ALL_POINTS_ON
#define LCD_BIAS_SET_1_9
#define LCD_BIAS_SET_1_7
#define LCD_INTERNAL_RESET
#define COM_OUTPUT_SCAN_NORMAL_DIRECTION
#define COM_OUTPUT_SCAN_REVERSE_DIRECTION
#define POWER_CONTROL_SET
//#define 